Create hallo_adhit.py
airlab-unsri/python-hello-world pull request #12
Opened 2019-10-28 04:21 UTC by adhitnugrah

menambahkan file hallo_adhit.py dan menuliskan 'hello world, be nice for me'

2019-10-28 04:52 UTC, ariefrahmansyah requested changes
Thanks for the PR, @adhitnugrah 
Btw, can you move your file to your own folder?

2019-10-28 12:04 UTC, ariefrahmansyah approved these changes
LGTM!

2019-10-28 15:14 UTC, adhitnugrah commented
tq ref

2019-10-29 15:12 UTC, Wentyocta approved these changes

2019-10-29 15:13 UTC, merged