Create hello.py
airlab-unsri/python-hello-world pull request #13
Opened 2019-10-28 12:20 UTC by Asura21

2019-10-28 13:22 UTC, ariefrahmansyah requested changes
Hi @Asura21 
Tolong filenya ditaruh di folder terpisah ya. Nama foldernya pake username Github kamu

2019-10-28 14:03 UTC, Asura21 commented
Okedeh kak

2019-10-28 15:29 UTC, ariefrahmansyah approved these changes
Niceee 👍

2019-10-29 13:06 UTC, Wentyocta approved these changes
cool !

2019-10-29 13:06 UTC, merged