Hello World
airlab-unsri/python-hello-world pull request #5
Opened 2019-10-27 01:37 UTC by victorronaldopasaribu

Hello

2019-10-27 04:36 UTC, ariefrahmansyah requested changes
Hi, @victorronaldopasaribu 
Kamu buat folder atas nama kamu sendiri ya. Bukan pake folder yang udah ada. Coba liat PR temen temen yang lain.

2019-10-27 05:38 UTC, ariefrahmansyah requested changes
nama filenya tolong diubah ya, jadi `hello_world.py`
untuk foldernya udah bener

2019-10-27 06:25 UTC, victorronaldopasaribu commented
sudah kak

2019-10-27 07:08 UTC, ariefrahmansyah approved these changes

2019-10-29 15:17 UTC, Wentyocta approved these changes

2019-10-29 15:18 UTC, merged